sudo: false
language: node_js
node_js:
- '6'
branches:
  only:
  - master
env:
  global:
    - secure: "xUObZDlF0pi1D5W3xa9/K02dKPMOTMydoWIB+uIKop1wMd4CagY9UnDXGFXCjt05Fuu1V54PSY3AsLCKg9PQLyLcNTfq4VoNX0MVj2GtGMe6Ob1AOiy6Sli+r8fcyb84QJaeVfqodGgjL0o+k74u2Ci58LA3XcuTvwAvuIoen1FdbyoEONjyPDKwB7cKAlmABxsOIQVBP1NEoYjhe7+Emb9lDAn82q3AsUEwEJw4RvqhORMXLmmc3pp/IvI8KdMWuZSmfDf+1ThkKwVvHJ8+VWTEr6aKSb9BWU3vh/x1MK7wy9TajOcjNLDd9AKMdyRtY+wuZLtq9T0O6gCzZwKz20gT3spV8DXROlYjTzj5cJ5FsohYNaBa3wVqyZG+SefmkRiu2gh4skuJK4VCX1W8rSjx4T+a/aCOGdrb+s1ZDNFdhabDz+RWxeyJsLRAyWO53+0ZA+n0HvQmoTsNEjpkyhlMiG1SOm5GYJK/PHOP6OtgOOJfVn0O/upbvicpJCJfk3nvwF+9vlkJt7wBf55qPae0ueWuR6BmssaOq9jvEsnrplcL1sgdmcjfFmgtAbuPyoU5lYO7mh9r8I8z0Ecg28/5yIgqKrKDGn+gcwa3QXKgSiiVy6Km5/PNOXuF+iRaIENmidum9iurujr0U3Tviq/d92xBz1DroNv2c3fRRgo="
before_deploy:
  - yarn build
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN
  local_dir: dist/
  keep-history: true
  on:
    branch: master
  edge:
    branch: pages-ivar-set
after_deploy:
  - chmod +x ./after_deploy.sh
  - "./after_deploy.sh"