sudo: false
language: node_js
node_js:
- '6'
branches:
  only:
  - master
env:
  global:
    - secure: "odAsYvKfSioYsUDDdUpJQe3V+UtqhbP5f7DpkpoW+PPe8HRDVOKVBPxTLGpqUug8BTHxCC5QiMwp/BcLKN+o+cILiRF13uFtz4KTBuCA1Y3BAQHssNVzAaABHGaFJzNGGidBBU3CWo8V2E1cVJ8VHRSw8UTxGLiARIOyMELfA10ixViGNjv1bR2Fobn8tnBxK5tz08m4x1KByI4PwRDE87pAIkREAfohT+KYuGYhYv01Cip52/I1ITxsgGeqFYvHHqua6L85Acz9Dt74Y17Lb9kCR03VYn/KCC9+xiYsoDUCCRyJUJKSnkIxxKT1BylcnXqALywmgCYaRewsDst7B/X/s3rkNKnD1YIHZu4anff9/lMqlZU1ZTjtkll5CAZR50jxIKj0XBvcPZCqf0sLPGPAPDVcy08sSQDhWoGu00uxDfhN3Bx8pDbddsmkdKJjMYb7LtOUIiCwJIus6Jq5hXYIaua7NmJHxxpk7VAlJczOAPb6Gr6BkHe4SgKvMJjCU4hm4WNxkCvgBY2Awr+2+RuuXH0cYtLmyen9ccEMWP90NZYkKyVecZnHLrqcG4HPS0+r6xyicBZdrpR8qX9eyKQl0FxHCKQek9RejOjx0779TGz5ZqY1j+oerp4aSDeMcXGWHz12Gl6E+ebWlPYfdc/OT4RmMctpt0Rs5IBdcZI="
before_deploy:
  - yarn build
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN
  local_dir: dist/
  keep-history: true
  on:
    branch: master
  edge:
    branch: pages-ivar-set
after_deploy:
  - chmod +x .travis/after_deploy.sh
  - .travis/after_deploy.sh