sudo: false
language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN
  local_dir: dist/
  on:
    branch: master
